//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public long ID { get; set; }
        public int Number_ticket { get; set; }
        public string Date { get; set; }
        public string Visit_purpose { get; set; }
        public double Price { get; set; }
        public long ID_diagnosis { get; set; }
        public long ID_doctor { get; set; }
        public long ID_patient { get; set; }
    
        public virtual Diagnosis Diagnosis { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
