//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnosis
    {
        public long ID { get; set; }
        public string Code_diagnosis { get; set; }
        public string Name_diagnosis { get; set; }
    
        public virtual Appointment Appointment { get; set; }
    }
}
